export const FETCH_USER_PENDING = 'FETCH_USER_PENDING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const LOAD_EPISODES_SUCCESS = 'LOAD_EPISODES_SUCCESS';
export const LOAD_EPISODES_FAIL = 'LOAD_EPISODES_FAIL';
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';
export const LOAD_CHARACTERS_FAIL = 'LOAD_CHARACTERS_FAIL';